version: '3'
services:
    servanttest:
        build: .
        image: servanttest
        command: servanttest
        expose:
            - "1234"
    nginx:
        build: ./nginx
        image: nginx
        ports:
            - "8080:80"
        depends_on:
            - servanttest
