# This YAML file describes your package. Stack will automatically generate a
# Cabal file when you run `stack build`. See the hpack website for help with
# this file: <https://github.com/sol/hpack>.
name: waitest
version: '0.0.0'
github: "githubuser/waitest"
license: MIT
author: "Author name here"
maintainer: "Author name here"
# synopsis: A new Haskeleton package.
# description: waitest is a new Haskeleton package.
# category: Other

extra-source-files:
- CHANGELOG.md
- LICENSE.md
- package.yaml
- README.md
- stack.yaml

ghc-options: -Wall

default-extensions:
  - OverloadedStrings
  - DeriveGeneric
  - FlexibleContexts
  - GADTs
  - RankNTypes
  - DuplicateRecordFields
  - GeneralizedNewtypeDeriving

library:
  dependencies:
  - base
  - wai
  - warp
  - http-types
  source-dirs: library

executables:
  waitest:
    source-dirs: executable
    main: Main.hs
    dependencies:
    - base
    - waitest
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    - -O2
benchmarks:
  waitest-benchmarks:
    source-dirs: benchmark
    main: Main.hs
    dependencies:
    - base
    - waitest
    - criterion
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N

tests:
  waitest-test-suite:
    source-dirs: test-suite
    main: Main.hs
    dependencies:
    - base
    - waitest
    - tasty
    - tasty-hspec
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
